# Generated by Django 4.1 on 2022-10-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Entry',
        ),
    ]
