# Generated by Django 4.1.2 on 2022-10-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0002_rename_todo_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(),
        ),
    ]
