# Generated by Django 4.1.2 on 2022-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0003_entry_location_alter_entry_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='entry',
            name='lon',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
