# Generated by Django 4.1.2 on 2022-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0005_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AddField(
            model_name='entry',
            name='picture',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
