# Generated by Django 4.1.2 on 2022-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0010_entry_name_alter_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
