# Generated by Django 4.1.2 on 2022-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0011_alter_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
