# Generated by Django 4.1.2 on 2022-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJXN', '0013_alter_entry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='address',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
